# Generated by Django 6.0.6 on 2026-06-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_state_voter_register_alter_unit_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='unit_name',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='name',
            new_name='ward_name',
        ),
        migrations.AddField(
            model_name='unit',
            name='local_government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.local_government'),
        ),
        migrations.AddField(
            model_name='unit',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.state'),
        ),
        migrations.AddField(
            model_name='unit',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.ward'),
        ),
        migrations.AddField(
            model_name='voter_register',
            name='local_government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.local_government'),
        ),
        migrations.AddField(
            model_name='voter_register',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.state'),
        ),
        migrations.AddField(
            model_name='voter_register',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.unit'),
        ),
        migrations.AddField(
            model_name='voter_register',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.ward'),
        ),
        migrations.AddField(
            model_name='ward',
            name='local_government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.local_government'),
        ),
        migrations.AddField(
            model_name='ward',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.state'),
        ),
    ]
