# Generated by Django 6.0.6 on 2026-06-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=60)),
                ('state_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Voter_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_code',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Local_government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=10)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.state')),
            ],
        ),
    ]
